---
Description: IAM User for GitHub to deploy slides to S3
Resources:
  GitHubUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref AWS::StackName
      Policies:
        - PolicyName: 'upload-to-s3'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:Put*'
                  - 's3:List*'
                  - 's3:Get*'
                Resource: '*'
