---
Description: Host a java application on beanstalk
Parameters:
  ApplicationName:
    Description: Name of the application
    Type: "String"
Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: 'elasticbeanstalk.amazonaws.com'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': elasticbeanstalk
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService'
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceProfileRole
  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: BucketAccess
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:Put*'
                Effect: Allow
                Resource: '*'
              - Sid: DynamodbAccess
                Action:
                  - 'dynamodb:Put*'
                  - 'dynamodb:Get*'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                Effect: Allow
                Resource: '*'
  DevEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      Description: !Join [ ' ', [ 'Dev environment for', !Ref Application ] ]
      EnvironmentName: !Join [ '-', [ !Ref Application, 'dev' ] ]
      SolutionStackName: '64bit Amazon Linux 2 v3.1.0 running Corretto 11'
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: 'IamInstanceProfile'
          Value: !Ref InstanceProfile
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: 'ServiceRole'
          Value: !Ref ServiceRole
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: 'HealthCheckPath'
          Value: '/actuator/health'
        - Namespace: 'aws:elasticbeanstalk:healthreporting:system'
          OptionName: 'SystemType'
          Value: 'enhanced'
  ImagesBucket:
    Type: AWS::S3::Bucket
  AlbumsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: !Join [ '-', [ !Ref Application, 'albums', 'dev' ] ]
  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "albumId"
          AttributeType: "S"
        - AttributeName: "uploadedAt"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "albumId"
          KeyType: "HASH"
        - AttributeName: "uploadedAt"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: !Join [ '-', [ !Ref Application, 'images', 'dev' ] ]
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: True
        HttpVersion: http2
        PriceClass: PriceClass_100
        Comment: !Ref AWS::StackName
        Origins:
          - Id: default
            DomainName: !GetAtt DevEnvironment.EndpointURL
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: default
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: True
          MinTTL: 60
          DefaultTTL: 300
          MaxTTL: 300
