name: 'Deploy'

on: push

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
      - run: yarn build
        env:
          CI: true
      - uses: unfor19/install-aws-cli-action@v1
      - name: Upload website
        run: |
          aws s3 sync build/ s3://${{ secrets.SLIDES_BUCKET_NAME }}/ --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}